project_name: mongo_update
database: sandbox
collection: bulk_update
logging:
  version: 1
  disable_existing_loggers: False
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      stream: ext://sys.stdout
    logfile:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      filename: "logs/app.log"
      maxBytes: 1000000
      backupCount: 3
    watchtower:
      class: watchtower.CloudWatchLogHandler
      level: DEBUG
      log_group_name: "test/mongo_update"
      log_group_retention_days: 3
      log_stream_name: "{logger_name}-{strftime:%y-%m-%d}"
      send_interval: 10
      create_log_group: True
  root:
    level: INFO
    propagate: True
    handlers:
      - console
      - watchtower
  loggers:
    botocore:
      level: ERROR
    boto3:
      level: ERROR
    urllib3:
      level: ERROR
    snowflake:
      level: ERROR
    filelock:
      level: ERROR
